apiVersion: v1
kind: Secret
metadata:
  name: hmp-secret
stringData:
  JWT_SECRET: "4jez3Ruh5sbVMChP"
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  REDIS_USER: "user"
  REDIS_PASSWORD: "password"
  DATABASE_URL: "postgres://user:password@postgres:5432/hmp-postgres?sslmode=disable"
